# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoilerplateApp' do
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
  pod 'GoogleMaps'
  end


